### ISSUE TITLE
Page hook changes meta tags

### ISSUE THREAD

**Issue by iZarif** [WonderCMS/wondercms#286]
Hello I installed WonderCMS 3.4.1 on my local server, created a page called "Product" and also created a simple plugin. 

The code for the plugin is
```php
<?php

global $Wcms;

$Wcms->addListener('page', 'displayProduct');

function displayProduct($args) {
    global $Wcms;

    if ($Wcms->currentPage != 'product') {
		return $args;
	}

	$args[0] .= 'Test content';

	return $args;
}`
```
After activating the plugin, the /product page looks like this
![src_2023-02-03_13-38-12](https://user-images.githubusercontent.com/22560266/216567791-236fec63-9c4c-4e2d-8346-fc74f1833e5f.png)
If you check the contents of the title, description or keywords meta tags, you will notice that the line 'Test content' has been added there, Is it supposed to be like this? How not to change the content of meta tags?

**Comment by robiso** [comment]
Hey @iZarif. This is expected behaviour since you are changing all the arguments for the page.

You can find different ways of setting the description and everything you need on here: https://github.com/WonderCMS/wondercms/wiki/Set-data-to-database

Let me know if this helps. If it doesn't, feel free to keep to continue the discussion and we'll reopen the issue.
